name: Prebuild iOS

on:
  workflow_dispatch:

jobs:
  prebuild-ios:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Expo Prebuild for iOS
        run: npx expo prebuild --platform ios